pusher_app_id: "2954"
pusher_key: "7381a978f7dd7f9a1117"
pusher_secret: "abdc3b896a0ffb85d373"

test:
  pusher_app_id: "5112"
  pusher_key: "ad69caf9a44dcac1fb28"
  pusher_secret: "83ca7aa160fedaf3b350"

  google_analytics_key: "UA-35722661-5"

test:
  google_analytics_key: ~

  stripe_api_key: "sk_live_dSqzdUq80sw9GWmuoI0qJ9rL"

ENV["stripe_api_key"] # => "sk_live_dSqzdUq80sw9GWmuoI0qJ9rL"
ENV.key?("stripe_api_key") # => true
ENV["google_analytics_key"] # => nil
ENV.key?("google_analytics_key") # => false

Figaro.env.stripe_api_key # => "sk_live_dSqzdUq80sw9GWmuoI0qJ9rL"
Figaro.env.stripe_api_key? # => true
Figaro.env.google_analytics_key # => nil
Figaro.env.google_analytics_key? # => false

AWS_ACCESS_KEY: "AKIAIABF2PH2HVTTDZUA"
AWS_SECRET_KEY: "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"
AWS_BUCKET: "editapp76"
